### ISSUE TITLE
Missing "release/RDRAND_Tester_Linux" file/directory

### ISSUE THREAD

**Issue by Ricky-Tigg** [cjee21/RDRAND-Tester#1]
**OS:** Linux, Fedora, edition 39. Code acquired with `git clone`.

Hello. Missing _release/RDRAND_Tester_Linux_ file/directory.
```
$ gcc RDRAND_Tester.c -o release/RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fstack-clash-protection -fcf-protection -Wl,-z,relro,-z,now,-pie,--hash-style=gnu,--no-copy-dt-needed-entries,--as-needed -s
/usr/bin/ld: cannot open output file release/RDRAND_Tester_Linux: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by cjee21** [comment]
Please manually create a `release` directory if it does not exist before executing the gcc command. Alternatively, change the `-o` parameter from `release` to a directory that exists.

**Comment by Ricky-Tigg** [comment]
```
$ touch ../RDRAND_Tester_Linux
$ gcc RDRAND_Tester.c -o ../RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fstack-clash-protection -fcf-protection -Wl,-z,relro,-z,now,-pie,--hash-style=gnu,--no-copy-dt-needed-entries,--as-needed -s
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/13/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a PIE object
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
```

**Comment by cjee21** [comment]
Try:
`gcc RDRAND_Tester.c -o ../RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -s`
The other options are good security practice but not essential to the functionality of this simple application.

Anyway, the errors seem to be a compiler related and not concerning the code of this application. I cannot help further as I am not familiar with Fedora and not an expert with GCC.

**Comment by Ricky-Tigg** [comment]
I noted that `touch ../<file>` was not needed prior to the execution of this `gcc` command. At last it the code is operational with this command you suggested and the `gcc` one that follows here.
```
$ find .. -maxdepth 1 -type f -ls
$ gcc RDRAND_Tester.c -o ../RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fstack-clash-protection -fcf-protection -s
$ find .. -maxdepth 1 -type f -ls
145658  24  -rwxr-xr-x  1 _  _  20544 Nov 10 17:12 ../RDRAND_Tester_Linux
```

**Comment by Ricky-Tigg** [comment]
I noted that `touch ../<file>` was not needed prior to the execution of this `gcc` command. This command you just suggested and the `gcc` one that here follows are executed without extra messages.
```
$ find .. -maxdepth 1 -type f -ls
$ gcc RDRAND_Tester.c -o ../RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fstack-clash-protection -fcf-protection -s
$ find .. -maxdepth 1 -type f -ls
145658  24  -rwxr-xr-x  1 _  _  20544 Nov 10 17:12 ../RDRAND_Tester_Linux
```

**Comment by Ricky-Tigg** [comment]
I noted that `touch ../<file>` was not needed prior to the execution of this `gcc` command. This command you just suggested and the `gcc` one that here follows are executed without extra messages. Time to test the binary file created by this process; `./RDRAND_Tester_Linux`. It is operational.
```
$ find .. -maxdepth 1 -type f -ls
$ gcc RDRAND_Tester.c -o ../RDRAND_Tester_Linux -Wall -Wconversion -Wformat-security -O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fstack-clash-protection -fcf-protection -s
$ find .. -maxdepth 1 -type f -ls
145658  24  -rwxr-xr-x  1 _  _  20544 Nov 10 17:12 ../RDRAND_Tester_Linux
```
